services:
  app:
    build: .
    container_name: mccallister-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/mccallister-db
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mccallister-db
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
